// Generated by the Class Generator.  DO NOT EDIT!

#import <Foundation/Foundation.h>
#import "__KBFontAwesomeResource.h"

@implementation KBFontAwesomeResource

+ (KBFontAwesomeCode)xwarrowleft {
    return 0xE900;
}

+ (KBFontAwesomeCode)xwarrowright {
    return 0xE901;
}

+ (KBFontAwesomeCode)xwclose {
    return 0xE902;
}

+ (KBFontAwesomeCode)xwpoint {
    return 0xE903;
}

+ (KBFontAwesomeCode)xwmore {
    return 0xE904;
}

+ (KBFontAwesomeCode)xwdownarrow {
    return 0xE905;
}

+ (KBFontAwesomeCode)xwuparrow {
    return 0xE906;
}

+ (KBFontAwesomeCode)xwfollow {
    return 0xE907;
}

+ (KBFontAwesomeCode)xwmutualattention {
    return 0xE908;
}

+ (KBFontAwesomeCode)xwplus {
    return 0xE909;
}

+ (KBFontAwesomeCode)xwminussign {
    return 0xE90A;
}

+ (KBFontAwesomeCode)xwmagnifier {
    return 0xE90B;
}

+ (KBFontAwesomeCode)xwmaximize {
    return 0xE90C;
}

+ (KBFontAwesomeCode)xwminimize {
    return 0xE90D;
}

+ (KBFontAwesomeCode)xwback {
    return 0xE90E;
}

+ (KBFontAwesomeCode)xwright {
    return 0xE90F;
}

+ (KBFontAwesomeCode)xwmax {
    return 0xE910;
}

+ (KBFontAwesomeCode)xwmin {
    return 0xE911;
}

+ (KBFontAwesomeCode)xwairplay {
    return 0xE912;
}

+ (KBFontAwesomeCode)xwphoto {
    return 0xE913;
}

+ (KBFontAwesomeCode)xwedit {
    return 0xE914;
}

+ (KBFontAwesomeCode)xwcomment {
    return 0xE915;
}

+ (KBFontAwesomeCode)xwnocomment {
    return 0xE916;
}

+ (KBFontAwesomeCode)xwshare {
    return 0xE917;
}

+ (KBFontAwesomeCode)xwdownload {
    return 0xE918;
}

+ (KBFontAwesomeCode)xwcomplaints {
    return 0xE919;
}

+ (KBFontAwesomeCode)xwfont {
    return 0xE91A;
}

+ (KBFontAwesomeCode)xwcollection {
    return 0xE91B;
}

+ (KBFontAwesomeCode)xwsmile {
    return 0xE91C;
}

+ (KBFontAwesomeCode)xwvoice {
    return 0xE91D;
}

+ (KBFontAwesomeCode)xwcamera {
    return 0xE91E;
}

+ (KBFontAwesomeCode)xwgif {
    return 0xE91F;
}

+ (KBFontAwesomeCode)xwimage {
    return 0xE920;
}

+ (KBFontAwesomeCode)xwcopylink {
    return 0xE921;
}

+ (KBFontAwesomeCode)xwcrop {
    return 0xE922;
}

+ (KBFontAwesomeCode)xwemail {
    return 0xE923;
}

+ (KBFontAwesomeCode)xwlike {
    return 0xE924;
}

+ (KBFontAwesomeCode)xwdislike {
    return 0xE925;
}

+ (KBFontAwesomeCode)xwlook {
    return 0xE926;
}

+ (KBFontAwesomeCode)xwlink {
    return 0xE927;
}

+ (KBFontAwesomeCode)xwbluetooth {
    return 0xE928;
}

+ (KBFontAwesomeCode)xwlock {
    return 0xE929;
}

+ (KBFontAwesomeCode)xwunlock {
    return 0xE92A;
}

+ (KBFontAwesomeCode)xwbell {
    return 0xE92B;
}

+ (KBFontAwesomeCode)xwbelloff {
    return 0xE92C;
}

+ (KBFontAwesomeCode)xwsound {
    return 0xE92D;
}

+ (KBFontAwesomeCode)xwnosound {
    return 0xE92E;
}

+ (KBFontAwesomeCode)xwphone {
    return 0xE92F;
}

+ (KBFontAwesomeCode)xwphoneoff {
    return 0xE930;
}

+ (KBFontAwesomeCode)xwplay {
    return 0xE931;
}

+ (KBFontAwesomeCode)xwstop {
    return 0xE932;
}

+ (KBFontAwesomeCode)xwvolume {
    return 0xE933;
}

+ (KBFontAwesomeCode)xwnotInterested {
    return 0xE934;
}

+ (KBFontAwesomeCode)xwrefresh {
    return 0xE935;
}

+ (KBFontAwesomeCode)xwposition {
    return 0xE936;
}

+ (KBFontAwesomeCode)xwradio {
    return 0xE937;
}

+ (KBFontAwesomeCode)xwwifi {
    return 0xE938;
}

+ (KBFontAwesomeCode)xwwifioff {
    return 0xE939;
}

+ (KBFontAwesomeCode)xwwechat {
    return 0xE93A;
}

+ (KBFontAwesomeCode)xwfillcomment {
    return 0xE93B;
}

+ (KBFontAwesomeCode)xwfillshare {
    return 0xE93C;
}

+ (KBFontAwesomeCode)xwfillwechat {
    return 0xE93D;
}

+ (KBFontAwesomeCode)xwfillcommen {
    return 0xE93E;
}

+ (KBFontAwesomeCode)xwonechili {
    return 0xE93F;
}

+ (KBFontAwesomeCode)xwtwochili {
    return 0xE940;
}

+ (KBFontAwesomeCode)xwKeyboard {
    return 0xE941;
}

+ (KBFontAwesomeCode)xwset {
    return 0xE942;
}

+ (KBFontAwesomeCode)xwflow {
    return 0xE943;
}

+ (KBFontAwesomeCode)xwbackup {
    return 0xE944;
}

+ (KBFontAwesomeCode)xwgame {
    return 0xE945;
}

+ (KBFontAwesomeCode)xwhelp {
    return 0xE946;
}

+ (KBFontAwesomeCode)xwreplay {
    return 0xE947;
}

+ (KBFontAwesomeCode)xwmeasurement {
    return 0xE948;
}

+ (KBFontAwesomeCode)xwdonation {
    return 0xE949;
}

+ (KBFontAwesomeCode)xwmoments {
    return 0xE94A;
}

+ (KBFontAwesomeCode)xwevenmore {
    return 0xE94B;
}

+ (KBFontAwesomeCode)xwmoon {
    return 0xE94C;
}

+ (KBFontAwesomeCode)xwhtlike {
    return 0xE94D;
}

+ (KBFontAwesomeCode)xwhtcomment {
    return 0xE94E;
}

+ (KBFontAwesomeCode)xwhtshare {
    return 0xE94F;
}

+ (KBFontAwesomeCode)xwhtissue {
    return 0xE950;
}

+ (KBFontAwesomeCode)xwfontchange {
    return 0xE951;
}

+ (KBFontAwesomeCode)xwcollectiond {
    return 0xE952;
}

+ (KBFontAwesomeCode)xwliked {
    return 0xE953;
}

+ (KBFontAwesomeCode)xwsun {
    return 0xE954;
}

+ (KBFontAwesomeCode)xwhtforbidcomment {
    return 0xE955;
}

+ (KBFontAwesomeCode)xwdelete {
    return 0xE956;
}

+ (KBFontAwesomeCode)xwnext {
    return 0xE957;
}

+ (KBFontAwesomeCode)xwdisliked {
    return 0xE958;
}

+ (KBFontAwesomeCode)xwuser {
    return 0xE959;
}

+ (KBFontAwesomeCode)xwimages {
    return 0xE95A;
}

+ (KBFontAwesomeCode)xwsplay {
    return 0xE95B;
}

+ (KBFontAwesomeCode)xwhtmessage {
    return 0xE95C;
}

+ (KBFontAwesomeCode)xwbangdan {
    return 0xE95D;
}

+ (KBFontAwesomeCode)xwfire {
    return 0xE95E;
}

+ (KBFontAwesomeCode)xwunlook {
    return 0xE95F;
}

+ (KBFontAwesomeCode)xwqrcode {
    return 0xE960;
}

+ (KBFontAwesomeCode)xwlist {
    return 0xE961;
}

+ (KBFontAwesomeCode)xwchat {
    return 0xE962;
}

+ (KBFontAwesomeCode)xwevenmorenew {
    return 0xE963;
}

+ (KBFontAwesomeCode)xwup {
    return 0xE964;
}

+ (KBFontAwesomeCode)xwtimey {
    return 0xE965;
}

+ (KBFontAwesomeCode)xwmunuy {
    return 0xE966;
}

+ (KBFontAwesomeCode)xwnexty {
    return 0xE967;
}

+ (KBFontAwesomeCode)xwplayy {
    return 0xE968;
}

+ (KBFontAwesomeCode)xwstopy {
    return 0xE969;
}

+ (KBFontAwesomeCode)xwemoji2 {
    return 0xE96A;
}

+ (KBFontAwesomeCode)xwcamera2 {
    return 0xE96B;
}

+ (KBFontAwesomeCode)xwimage2 {
    return 0xE96C;
}

+ (KBFontAwesomeCode)xwvoice2 {
    return 0xE96D;
}

+ (KBFontAwesomeCode)xwgif2 {
    return 0xE96E;
}

+ (KBFontAwesomeCode)xwkeyboard2 {
    return 0xE96F;
}

+ (KBFontAwesomeCode)xwhuati2 {
    return 0xE970;
}

+ (KBFontAwesomeCode)xwlight {
    return 0xE971;
}

+ (KBFontAwesomeCode)xwtranspond {
    return 0xE972;
}

+ (KBFontAwesomeCode)xwzhuanfa {
    return 0xE973;
}

+ (KBFontAwesomeCode)xwpicnew {
    return 0xE974;
}

+ (KBFontAwesomeCode)xwzhuanfaxia {
    return 0xE975;
}

+ (KBFontAwesomeCode)xwzhuanfanew {
    return 0xE976;
}

+ (KBFontAwesomeCode)xwedit20 {
    return 0xE977;
}

+ (KBFontAwesomeCode)video20 {
    return 0xE978;
}

+ (KBFontAwesomeCode)share24 {
    return 0xE979;
}

+ (KBFontAwesomeCode)xwhuang1 {
    return 0xE97A;
}

+ (KBFontAwesomeCode)xwadd24 {
    return 0xE97B;
}

+ (KBFontAwesomeCode)xwping {
    return 0xE97C;
}

+ (KBFontAwesomeCode)xwla1 {
    return 0xE97D;
}

+ (KBFontAwesomeCode)xwla2 {
    return 0xE97E;
}

+ (KBFontAwesomeCode)xwtui24 {
    return 0xE97F;
}

+ (KBFontAwesomeCode)xwclosex {
    return 0xE980;
}

+ (KBFontAwesomeCode)xwzhengwen {
    return 0xE981;
}

+ (KBFontAwesomeCode)xwzheng {
    return 0xE982;
}

+ (KBFontAwesomeCode)xwguan {
    return 0xE983;
}

+ (KBFontAwesomeCode)xwshoucang {
    return 0xE984;
}

+ (KBFontAwesomeCode)xwyishou {
    return 0xE985;
}

+ (KBFontAwesomeCode)xwduigou {
    return 0xE986;
}

+ (KBFontAwesomeCode)xwxg {
    return 0xE987;
}

+ (KBFontAwesomeCode)xwdanmuopen {
    return 0xE988;
}

+ (KBFontAwesomeCode)xwdanmuclose {
    return 0xE989;
}

+ (KBFontAwesomeCode)xwsofa {
    return 0xE98A;
}

+ (KBFontAwesomeCode)xwmenuwrite {
    return 0xE98B;
}

+ (KBFontAwesomeCode)xwmenucopy {
    return 0xE98C;
}

+ (KBFontAwesomeCode)xwmenushare {
    return 0xE98D;
}

+ (KBFontAwesomeCode)xwmenuerror {
    return 0xE98E;
}

+ (KBFontAwesomeCode)xwmenusearch {
    return 0xE98F;
}

+ (KBFontAwesomeCode)xwmenurocket {
    return 0xE990;
}

+ (KBFontAwesomeCode)xwhnext {
    return 0xE991;
}

+ (KBFontAwesomeCode)xwhpre {
    return 0xE992;
}

+ (KBFontAwesomeCode)xwhspeed {
    return 0xE993;
}

+ (KBFontAwesomeCode)xwhaudio {
    return 0xE994;
}

+ (KBFontAwesomeCode)xwhtiming {
    return 0xE995;
}

+ (KBFontAwesomeCode)xwhsummary {
    return 0xE996;
}

+ (KBFontAwesomeCode)xwhfulltext {
    return 0xE997;
}

+ (KBFontAwesomeCode)xwhtime {
    return 0xE998;
}

+ (KBFontAwesomeCode)xwhheadset {
    return 0xE999;
}

+ (KBFontAwesomeCode)xwhspeed07 {
    return 0xE99A;
}

+ (KBFontAwesomeCode)xwhspeed10 {
    return 0xE99B;
}

+ (KBFontAwesomeCode)xwhspeed12 {
    return 0xE99C;
}

+ (KBFontAwesomeCode)xwhspeed15 {
    return 0xE99D;
}

+ (KBFontAwesomeCode)xwbarlook {
    return 0xE99E;
}

+ (KBFontAwesomeCode)xwbarcomment {
    return 0xE99F;
}

+ (KBFontAwesomeCode)xwbarhot {
    return 0xE9A0;
}

+ (KBFontAwesomeCode)xwbarhot2 {
    return 0xE9A1;
}

+ (KBFontAwesomeCode)xwbarwechat {
    return 0xE9A2;
}

+ (KBFontAwesomeCode)xwbarpublish {
    return 0xE9A3;
}

+ (KBFontAwesomeCode)xwhshare {
    return 0xE9A4;
}

+ (KBFontAwesomeCode)xwlineation {
    return 0xE9A5;
}

+ (KBFontAwesomeCode)xwhiddenline {
    return 0xE9A6;
}

+ (KBFontAwesomeCode)xwcopyline {
    return 0xE9A7;
}

+ (KBFontAwesomeCode)xwfriendcircleline {
    return 0xE9A8;
}

+ (KBFontAwesomeCode)xwlogin {
    return 0xE9A9;
}

+ (KBFontAwesomeCode)xwqiyewechatline {
    return 0xE9AA;
}

+ (KBFontAwesomeCode)xwqqline {
    return 0xE9AB;
}

+ (KBFontAwesomeCode)xwqzoneline {
    return 0xE9AC;
}

+ (KBFontAwesomeCode)xwrocket1 {
    return 0xE9AD;
}

+ (KBFontAwesomeCode)xwweiboline {
    return 0xE9AE;
}

+ (KBFontAwesomeCode)xwrockrt {
    return 0xE9AF;
}

+ (KBFontAwesomeCode)xwbarlook1 {
    return 0xE9B0;
}

+ (KBFontAwesomeCode)xwpLikeN {
    return 0xE9B1;
}

+ (KBFontAwesomeCode)xwpLikeD {
    return 0xE9B2;
}

+ (KBFontAwesomeCode)xwpComment {
    return 0xE9B3;
}

+ (KBFontAwesomeCode)xwpShare {
    return 0xE9B4;
}

+ (KBFontAwesomeCode)xwpDislike {
    return 0xE9B5;
}

+ (KBFontAwesomeCode)xwcomment010 {
    return 0xE9B6;
}

+ (KBFontAwesomeCode)xwhotmore {
    return 0xE9B7;
}

+ (KBFontAwesomeCode)xwm24 {
    return 0xE9B8;
}

+ (KBFontAwesomeCode)xwErjiNew {
    return 0xE9B9;
}

+ (KBFontAwesomeCode)xwTinyview {
    return 0xE9BA;
}

+ (KBFontAwesomeCode)xwTinyuser {
    return 0xE9BB;
}

+ (KBFontAwesomeCode)xwTinyimg {
    return 0xE9BC;
}

+ (KBFontAwesomeCode)xws21 {
    return 0xE9BD;
}

+ (KBFontAwesomeCode)xws24 {
    return 0xE9BE;
}

+ (KBFontAwesomeCode)xws2 {
    return 0xE9BF;
}

+ (KBFontAwesomeCode)xws23 {
    return 0xE9C0;
}

+ (KBFontAwesomeCode)xwShare1s {
    return 0xE9C1;
}

+ (KBFontAwesomeCode)xwWs1 {
    return 0xE9C2;
}

+ (KBFontAwesomeCode)xwsp2 {
    return 0xE9C3;
}

+ (KBFontAwesomeCode)xwSp1 {
    return 0xE9C4;
}

+ (KBFontAwesomeCode)xws233 {
    return 0xE9C5;
}

+ (KBFontAwesomeCode)unie9c6 {
    return 0xE9C6;
}

+ (KBFontAwesomeCode)xwHotUp {
    return 0xE9C7;
}

+ (KBFontAwesomeCode)xwWs11 {
    return 0xE9C8;
}

+ (KBFontAwesomeCode)searchRight {
    return 0xE9C9;
}

+ (KBFontAwesomeCode)xwVideoLine {
    return 0xE9CA;
}

+ (KBFontAwesomeCode)xwSpj {
    return 0xE9CB;
}

+ (KBFontAwesomeCode)xwsj2 {
    return 0xE9CC;
}

+ (KBFontAwesomeCode)xwRadioNew {
    return 0xE9CD;
}

+ (KBFontAwesomeCode)xwTinyplay {
    return 0xE9CE;
}

+ (KBFontAwesomeCode)xwGif {
    return 0xE9CF;
}

+ (KBFontAwesomeCode)xwbellNew {
    return 0xE9D0;
}

+ (KBFontAwesomeCode)xwCai {
    return 0xE9D1;
}

+ (KBFontAwesomeCode)xwFuzhi {
    return 0xE9D2;
}

+ (KBFontAwesomeCode)xwMoreNew {
    return 0xE9D3;
}

+ (KBFontAwesomeCode)xwVideozhuanji {
    return 0xE9D4;
}

+ (KBFontAwesomeCode)xwVideozhuanjixian {
    return 0xE9D5;
}

+ (KBFontAwesomeCode)xwVoice24 {
    return 0xE9D6;
}

+ (KBFontAwesomeCode)xwQrcode {
    return 0xE9D7;
}

+ (KBFontAwesomeCode)xwGou24 {
    return 0xE9D8;
}

+ (KBFontAwesomeCode)arrowsDown {
    return 0xE9D9;
}

+ (KBFontAwesomeCode)xwLike3 {
    return 0xE9DA;
}

+ (KBFontAwesomeCode)xwDoutu1 {
    return 0xE9DB;
}

+ (KBFontAwesomeCode)xwXiaochuang {
    return 0xE9DC;
}

+ (KBFontAwesomeCode)xwfireline {
    return 0xE9DD;
}

+ (KBFontAwesomeCode)tuiRegular {
    return 0xE9DE;
}

+ (KBFontAwesomeCode)tuiBold {
    return 0xE9DF;
}

+ (KBFontAwesomeCode)faceiconTui {
    return 0xE9E0;
}

+ (KBFontAwesomeCode)shareRegular {
    return 0xE9E1;
}

+ (KBFontAwesomeCode)shareBold {
    return 0xE9E2;
}

+ (KBFontAwesomeCode)thumbupRegular {
    return 0xE9E3;
}

+ (KBFontAwesomeCode)thumbupBold {
    return 0xE9E4;
}

+ (KBFontAwesomeCode)faceiconThumbup {
    return 0xE9E5;
}

+ (KBFontAwesomeCode)commentRegular {
    return 0xE9E6;
}

+ (KBFontAwesomeCode)commentBold {
    return 0xE9E7;
}

+ (KBFontAwesomeCode)mainbodyRegular {
    return 0xE9E8;
}

+ (KBFontAwesomeCode)mainbodyBold {
    return 0xE9E9;
}

+ (KBFontAwesomeCode)commentHot1 {
    return 0xE9EA;
}

+ (KBFontAwesomeCode)commentHot2svg {
    return 0xE9EB;
}

+ (KBFontAwesomeCode)wechatRegular {
    return 0xE9EC;
}

+ (KBFontAwesomeCode)wechatBold {
    return 0xE9ED;
}

+ (KBFontAwesomeCode)videoupRegular {
    return 0xE9EE;
}

+ (KBFontAwesomeCode)videoupBold {
    return 0xE9EF;
}

+ (KBFontAwesomeCode)emojiRegular {
    return 0xE9F0;
}

+ (KBFontAwesomeCode)emojiBold {
    return 0xE9F1;
}

+ (KBFontAwesomeCode)photoRegular {
    return 0xE9F2;
}

+ (KBFontAwesomeCode)photoBold {
    return 0xE9F3;
}

+ (KBFontAwesomeCode)backRegular {
    return 0xE9F4;
}

+ (KBFontAwesomeCode)backBold {
    return 0xE9F5;
}

+ (KBFontAwesomeCode)rightRegular {
    return 0xE9F6;
}

+ (KBFontAwesomeCode)rightBold {
    return 0xE9F7;
}

+ (KBFontAwesomeCode)more {
    return 0xE9F8;
}

+ (KBFontAwesomeCode)faceiconPen {
    return 0xE9F9;
}

+ (KBFontAwesomeCode)noCommentRegular {
    return 0xE9FA;
}

+ (KBFontAwesomeCode)noCommentBold {
    return 0xE9FB;
}

+ (KBFontAwesomeCode)thumbdownRegular {
    return 0xE9FC;
}

+ (KBFontAwesomeCode)thumdownBold {
    return 0xE9FD;
}

+ (KBFontAwesomeCode)faceiconThumdown {
    return 0xE9FE;
}

+ (KBFontAwesomeCode)zhuizongRegular {
    return 0xE9FF;
}

+ (KBFontAwesomeCode)zhuizongBold {
    return 0xEA00;
}

+ (KBFontAwesomeCode)fullscreenRegular {
    return 0xEA01;
}

+ (KBFontAwesomeCode)fullscreenBold {
    return 0xEA02;
}

+ (KBFontAwesomeCode)xwSignal {
    return 0xEA03;
}

+ (KBFontAwesomeCode)searchRegular {
    return 0xEA04;
}

+ (KBFontAwesomeCode)searchBold {
    return 0xEA05;
}

+ (KBFontAwesomeCode)topicRegular {
    return 0xEA06;
}

+ (KBFontAwesomeCode)topicBold {
    return 0xEA07;
}

+ (KBFontAwesomeCode)sharePosterRegular {
    return 0xEA08;
}

+ (KBFontAwesomeCode)sharePosterBold {
    return 0xEA09;
}

+ (KBFontAwesomeCode)copyRegular {
    return 0xEA0A;
}

+ (KBFontAwesomeCode)copyBold {
    return 0xEA0B;
}

+ (KBFontAwesomeCode)tishiRegular {
    return 0xEA0C;
}

+ (KBFontAwesomeCode)tishiBold {
    return 0xEA0D;
}

+ (KBFontAwesomeCode)faceiconTishi {
    return 0xEA0E;
}

+ (KBFontAwesomeCode)collectRegular {
    return 0xEA0F;
}

+ (KBFontAwesomeCode)collectBold {
    return 0xEA10;
}

+ (KBFontAwesomeCode)faceiconCollect {
    return 0xEA11;
}

+ (KBFontAwesomeCode)darkmodeRegular {
    return 0xEA12;
}

+ (KBFontAwesomeCode)darkmodeBold {
    return 0xEA13;
}

+ (KBFontAwesomeCode)followingRegular {
    return 0xEA14;
}

+ (KBFontAwesomeCode)followingBold {
    return 0xEA15;
}

+ (KBFontAwesomeCode)goldcoinRegular {
    return 0xEA16;
}

+ (KBFontAwesomeCode)goldcoinBold {
    return 0xEA17;
}

+ (KBFontAwesomeCode)hongbaoRegular {
    return 0xEA18;
}

+ (KBFontAwesomeCode)hongbaoBold {
    return 0xEA19;
}

+ (KBFontAwesomeCode)identificationRegular {
    return 0xEA1A;
}

+ (KBFontAwesomeCode)identificationBold {
    return 0xEA1B;
}

+ (KBFontAwesomeCode)lightmodeRegular {
    return 0xEA1C;
}

+ (KBFontAwesomeCode)lightmodeBold {
    return 0xEA1D;
}

+ (KBFontAwesomeCode)messageRegular {
    return 0xEA1E;
}

+ (KBFontAwesomeCode)messageBold {
    return 0xEA1F;
}

+ (KBFontAwesomeCode)novelRegular {
    return 0xEA20;
}

+ (KBFontAwesomeCode)novelBold {
    return 0xEA21;
}

+ (KBFontAwesomeCode)radioRegular {
    return 0xEA22;
}

+ (KBFontAwesomeCode)radioBold {
    return 0xEA23;
}

+ (KBFontAwesomeCode)simcardRegular {
    return 0xEA24;
}

+ (KBFontAwesomeCode)simcardBold {
    return 0xEA25;
}

+ (KBFontAwesomeCode)walletRegular {
    return 0xEA26;
}

+ (KBFontAwesomeCode)walletBold {
    return 0xEA27;
}

+ (KBFontAwesomeCode)timingRegular {
    return 0xEA28;
}

+ (KBFontAwesomeCode)timingBold {
    return 0xEA29;
}

+ (KBFontAwesomeCode)closedStyle2Regular {
    return 0xEA2A;
}

+ (KBFontAwesomeCode)closedStyle2Bold {
    return 0xEA2B;
}

+ (KBFontAwesomeCode)faceiconClosed {
    return 0xEA2C;
}

+ (KBFontAwesomeCode)closedStyle1Regular {
    return 0xEA2D;
}

+ (KBFontAwesomeCode)closedStyle1Bold {
    return 0xEA2E;
}

+ (KBFontAwesomeCode)radio2Regular {
    return 0xEA2F;
}

+ (KBFontAwesomeCode)radio2Bold {
    return 0xEA30;
}

+ (KBFontAwesomeCode)radioIngRegular {
    return 0xEA31;
}

+ (KBFontAwesomeCode)noticeRegular {
    return 0xEA32;
}

+ (KBFontAwesomeCode)noticeBold {
    return 0xEA33;
}

+ (KBFontAwesomeCode)noticeNoRegular {
    return 0xEA34;
}

+ (KBFontAwesomeCode)noticeNoBold {
    return 0xEA35;
}

+ (KBFontAwesomeCode)faceiconNotice {
    return 0xEA36;
}

+ (KBFontAwesomeCode)locationRegular {
    return 0xEA37;
}

+ (KBFontAwesomeCode)locationBold {
    return 0xEA38;
}

+ (KBFontAwesomeCode)faceiconLocation {
    return 0xEA39;
}

+ (KBFontAwesomeCode)downStyle1Regular {
    return 0xEA3A;
}

+ (KBFontAwesomeCode)downStyle1Bold {
    return 0xEA3B;
}

+ (KBFontAwesomeCode)downStyle2Regular {
    return 0xEA3C;
}

+ (KBFontAwesomeCode)downStyle2Bold {
    return 0xEA3D;
}

+ (KBFontAwesomeCode)faciconDown {
    return 0xEA3E;
}

+ (KBFontAwesomeCode)cameraRegular {
    return 0xEA3F;
}

+ (KBFontAwesomeCode)cameraBold {
    return 0xEA40;
}

+ (KBFontAwesomeCode)fontsizeARegular {
    return 0xEA41;
}

+ (KBFontAwesomeCode)fontsizeABold {
    return 0xEA42;
}

+ (KBFontAwesomeCode)fontsizeBRegular {
    return 0xEA43;
}

+ (KBFontAwesomeCode)fontsizeBBold {
    return 0xEA44;
}

+ (KBFontAwesomeCode)xwPublic {
    return 0xEA45;
}

+ (KBFontAwesomeCode)huaweiPhone {
    return 0xEA46;
}

+ (KBFontAwesomeCode)backtopRegular {
    return 0xEA47;
}

+ (KBFontAwesomeCode)backtopBold {
    return 0xEA48;
}

+ (KBFontAwesomeCode)addUserRegular {
    return 0xEA49;
}

+ (KBFontAwesomeCode)addUserBold {
    return 0xEA4A;
}

+ (KBFontAwesomeCode)faceiconMainbody {
    return 0xEA4B;
}

+ (KBFontAwesomeCode)fansRegular {
    return 0xEA4C;
}

+ (KBFontAwesomeCode)fansBold {
    return 0xEA4D;
}

+ (KBFontAwesomeCode)faceiconFans {
    return 0xEA4E;
}

+ (KBFontAwesomeCode)pickRegular {
    return 0xEA4F;
}

+ (KBFontAwesomeCode)pickBold {
    return 0xEA50;
}

+ (KBFontAwesomeCode)faceiconPick {
    return 0xEA51;
}

+ (KBFontAwesomeCode)faceiconMessage {
    return 0xEA52;
}

+ (KBFontAwesomeCode)faceiconAdd {
    return 0xEA53;
}

+ (KBFontAwesomeCode)deleteRegular {
    return 0xEA54;
}

+ (KBFontAwesomeCode)deleteBold {
    return 0xEA55;
}

+ (KBFontAwesomeCode)dateRegular {
    return 0xEA56;
}

+ (KBFontAwesomeCode)dateBold {
    return 0xEA57;
}

+ (KBFontAwesomeCode)likeRegular {
    return 0xEA58;
}

+ (KBFontAwesomeCode)likeBold {
    return 0xEA59;
}

+ (KBFontAwesomeCode)likeNoBold {
    return 0xEA5A;
}

+ (KBFontAwesomeCode)likeNoRegular {
    return 0xEA5B;
}

+ (KBFontAwesomeCode)likeFaceicon {
    return 0xEA5C;
}

+ (KBFontAwesomeCode)addRegular {
    return 0xEA5D;
}

+ (KBFontAwesomeCode)addBold {
    return 0xEA5E;
}

+ (KBFontAwesomeCode)rotationRegular {
    return 0xEA5F;
}

+ (KBFontAwesomeCode)rotationBold {
    return 0xEA60;
}

+ (KBFontAwesomeCode)unlockRegular {
    return 0xEA61;
}

+ (KBFontAwesomeCode)unlockBold {
    return 0xEA62;
}

+ (KBFontAwesomeCode)lockRegular {
    return 0xEA63;
}

+ (KBFontAwesomeCode)lockBold {
    return 0xEA64;
}

+ (KBFontAwesomeCode)speed75Regular {
    return 0xEA65;
}

+ (KBFontAwesomeCode)speed0Regular {
    return 0xEA66;
}

+ (KBFontAwesomeCode)speed25Regular {
    return 0xEA67;
}

+ (KBFontAwesomeCode)speed5Regular {
    return 0xEA68;
}

+ (KBFontAwesomeCode)speed0Regular1 {
    return 0xEA69;
}

+ (KBFontAwesomeCode)lightSetRegular {
    return 0xEA6A;
}

+ (KBFontAwesomeCode)lightSetBold {
    return 0xEA6B;
}

+ (KBFontAwesomeCode)sortBaRegular {
    return 0xEA6C;
}

+ (KBFontAwesomeCode)sortBaBold {
    return 0xEA6D;
}

+ (KBFontAwesomeCode)sortAbRegular {
    return 0xEA6E;
}

+ (KBFontAwesomeCode)sortAbBold {
    return 0xEA6F;
}

+ (KBFontAwesomeCode)shareGongyiRegular {
    return 0xEA70;
}

+ (KBFontAwesomeCode)shareGongyiBold {
    return 0xEA71;
}

+ (KBFontAwesomeCode)aiteRegular {
    return 0xEA72;
}

+ (KBFontAwesomeCode)aiteBold {
    return 0xEA73;
}

+ (KBFontAwesomeCode)tiwenRegular {
    return 0xEA74;
}

+ (KBFontAwesomeCode)tiwenBold {
    return 0xEA75;
}

+ (KBFontAwesomeCode)tiwenFaceicon {
    return 0xEA76;
}

+ (KBFontAwesomeCode)qunliaoRegular {
    return 0xEA77;
}

+ (KBFontAwesomeCode)historyRegular {
    return 0xEA78;
}

+ (KBFontAwesomeCode)historyBold {
    return 0xEA79;
}

+ (KBFontAwesomeCode)thingFaceicon {
    return 0xEA7A;
}

+ (KBFontAwesomeCode)liveNew {
    return 0xEA7B;
}

+ (KBFontAwesomeCode)feedbackNew {
    return 0xEA7C;
}

+ (KBFontAwesomeCode)hashtagRegular {
    return 0xEA7D;
}

+ (KBFontAwesomeCode)hashtagBold {
    return 0xEA7E;
}

+ (KBFontAwesomeCode)followinglistRegular {
    return 0xEA7F;
}

+ (KBFontAwesomeCode)followinglistBold {
    return 0xEA80;
}

+ (KBFontAwesomeCode)minimizeRegular {
    return 0xEA81;
}

+ (KBFontAwesomeCode)minimizeBold {
    return 0xEA82;
}

+ (KBFontAwesomeCode)viewNoRegular {
    return 0xEA83;
}

+ (KBFontAwesomeCode)viewNoBold {
    return 0xEA84;
}

+ (KBFontAwesomeCode)settingRegular {
    return 0xEA85;
}

+ (KBFontAwesomeCode)settingBold {
    return 0xEA86;
}

+ (KBFontAwesomeCode)dingzhi {
    return 0xEA87;
}

+ (KBFontAwesomeCode)faceiconVideoNew {
    return 0xEA88;
}

+ (KBFontAwesomeCode)faceiconCommentNew {
    return 0xEA89;
}

+ (KBFontAwesomeCode)faceiconViewNew {
    return 0xEA8A;
}

+ (KBFontAwesomeCode)faceiconVideoup {
    return 0xEA8B;
}

+ (KBFontAwesomeCode)faceiconQq {
    return 0xEA8C;
}

+ (KBFontAwesomeCode)fenestrule {
    return 0xEA8D;
}

+ (KBFontAwesomeCode)restore {
    return 0xEA8E;
}

+ (KBFontAwesomeCode)faceiconPlane {
    return 0xEA8F;
}

+ (KBFontAwesomeCode)shaixuan {
    return 0xEA90;
}

+ (KBFontAwesomeCode)breaknews {
    return 0xEA91;
}

+ (KBFontAwesomeCode)readRegular {
    return 0xEA92;
}

+ (KBFontAwesomeCode)readBold {
    return 0xEA93;
}

+ (KBFontAwesomeCode)phone {
    return 0xEA94;
}

+ (KBFontAwesomeCode)editRegular {
    return 0xEA95;
}

+ (KBFontAwesomeCode)editBold {
    return 0xEA96;
}

+ (KBFontAwesomeCode)xwAdd2Regular {
    return 0xEA97;
}

+ (KBFontAwesomeCode)xwAdd2Bold {
    return 0xEA98;
}

+ (KBFontAwesomeCode)xwAdd2Faceicon {
    return 0xEA99;
}

+ (KBFontAwesomeCode)xwLinkRegular {
    return 0xEA9A;
}

+ (KBFontAwesomeCode)xwLinkBold {
    return 0xEA9B;
}

+ (KBFontAwesomeCode)xwJianpingRegular {
    return 0xEA9C;
}

+ (KBFontAwesomeCode)xwJianpingBold {
    return 0xEA9D;
}

+ (KBFontAwesomeCode)xwFilterRegular {
    return 0xEA9E;
}

+ (KBFontAwesomeCode)xwFilterBold {
    return 0xEA9F;
}

+ (KBFontAwesomeCode)xwVideoTopicRegular {
    return 0xEAA0;
}

+ (KBFontAwesomeCode)xwVideoTopicBold {
    return 0xEAA1;
}

+ (KBFontAwesomeCode)faceiconVideoTopic {
    return 0xEAA2;
}

+ (KBFontAwesomeCode)upStyle2Regular {
    return 0xEAA3;
}

+ (KBFontAwesomeCode)upStyle2Bold {
    return 0xEAA4;
}

+ (KBFontAwesomeCode)xwLahei {
    return 0xEAA5;
}

+ (KBFontAwesomeCode)xwLaheiCancel {
    return 0xEAA6;
}

+ (KBFontAwesomeCode)xwZhidingCancel {
    return 0xEAA7;
}

+ (KBFontAwesomeCode)xwZhiding {
    return 0xEAA8;
}

+ (KBFontAwesomeCode)xwThingRegular {
    return 0xEAA9;
}

+ (KBFontAwesomeCode)xwThingBold {
    return 0xEAAA;
}

+ (KBFontAwesomeCode)xwTimeline1 {
    return 0xEAAB;
}

+ (KBFontAwesomeCode)xwTimeline2 {
    return 0xEAAD;
}

+ (KBFontAwesomeCode)xwMsgProfile {
    return 0xEAAF;
}

+ (KBFontAwesomeCode)xwScanning {
    return 0xEAB0;
}

+ (KBFontAwesomeCode)xwFlagRegular {
    return 0xEAB1;
}

+ (KBFontAwesomeCode)xwFlagBold {
    return 0xEAB2;
}

+ (KBFontAwesomeCode)xwFastplayRegular {
    return 0xEAB3;
}

+ (KBFontAwesomeCode)xwFaceiconVerticalscreen {
    return 0xEAB4;
}

+ (KBFontAwesomeCode)xwHd {
    return 0xEAB5;
}

+ (KBFontAwesomeCode)xwLiveManage {
    return 0xEAB6;
}

+ (KBFontAwesomeCode)xwDingzhiNew {
    return 0xEAB7;
}

+ (KBFontAwesomeCode)xwAgree {
    return 0xEAB8;
}

+ (KBFontAwesomeCode)xwDisagree {
    return 0xEAB9;
}

+ (KBFontAwesomeCode)xwAgreeFaceicon {
    return 0xEABA;
}

+ (KBFontAwesomeCode)xwDisagreeFaceicon {
    return 0xEABB;
}

+ (KBFontAwesomeCode)xwTouping {
    return 0xEABC;
}

+ (KBFontAwesomeCode)xwQiehuan {
    return 0xEABD;
}

+ (KBFontAwesomeCode)xwTuichu {
    return 0xEABE;
}

+ (KBFontAwesomeCode)xwFeedback {
    return 0xEABF;
}

+ (KBFontAwesomeCode)xwHuidaRegular {
    return 0xEAC0;
}

+ (KBFontAwesomeCode)xwHuidaBold {
    return 0xEAC1;
}

+ (KBFontAwesomeCode)xwDownload {
    return 0xEAC2;
}

+ (KBFontAwesomeCode)xwYinhao1 {
    return 0xEAC3;
}

+ (KBFontAwesomeCode)xwYinhao2 {
    return 0xEAC4;
}

+ (KBFontAwesomeCode)xwPrivacyOff {
    return 0xEAC5;
}

+ (KBFontAwesomeCode)xwPrivacyOn {
    return 0xEAC6;
}

+ (KBFontAwesomeCode)xwDanxuan {
    return 0xEAC7;
}

+ (KBFontAwesomeCode)xwXunhuan {
    return 0xEAC8;
}

+ (KBFontAwesomeCode)xwLianbo {
    return 0xEAC9;
}

+ (KBFontAwesomeCode)xwLianboGuanbi {
    return 0xEACA;
}

+ (KBFontAwesomeCode)xwTextSelected {
    return 0xEACB;
}

+ (KBFontAwesomeCode)xwTextBold {
    return 0xEACC;
}

+ (KBFontAwesomeCode)xwDownStyle3 {
    return 0xEACD;
}

+ (KBFontAwesomeCode)xwVideoSkip {
    return 0xEACE;
}

+ (KBFontAwesomeCode)xwWenbenYinhao1 {
    return 0xEACF;
}

+ (KBFontAwesomeCode)xwWenbenYinhao2 {
    return 0xEAD0;
}

+ (KBFontAwesomeCode)xwWenbenGantan {
    return 0xEAD1;
}

+ (KBFontAwesomeCode)xwVideoRank {
    return 0xEAD2;
}

+ (KBFontAwesomeCode)xwTap {
    return 0xEAD3;
}

+ (KBFontAwesomeCode)xwRevoke {
    return 0xEAD4;
}

+ (KBFontAwesomeCode)xwRedo {
    return 0xEAD5;
}

+ (KBFontAwesomeCode)xw07 {
    return 0xEAD6;
}

+ (KBFontAwesomeCode)xw10 {
    return 0xEAD7;
}

+ (KBFontAwesomeCode)xw12 {
    return 0xEAD8;
}

+ (KBFontAwesomeCode)xw15 {
    return 0xEAD9;
}

+ (KBFontAwesomeCode)xw20 {
    return 0xEAAC;
}

+ (KBFontAwesomeCode)xwhspeed20 {
    return 0xEAAE;
}

+ (KBFontAwesomeCode)xwWen {
    return 0xEADA;
}

+ (KBFontAwesomeCode)xwShuping {
    return 0xEADB;
}

+ (KBFontAwesomeCode)xwYujing {
    return 0xEADC;
}

+ (KBFontAwesomeCode)xwTiwen {
    return 0xEADD;
}

+ (KBFontAwesomeCode)xwZhankai {
    return 0xEADE;
}

+ (KBFontAwesomeCode)xwXieyi {
    return 0xEADF;
}

+ (KBFontAwesomeCode)xwRadioVoice {
    return 0xEAE0;
}

+ (KBFontAwesomeCode)xwUserNew {
    return 0xEAE1;
}

+ (KBFontAwesomeCode)xwVideoSet {
    return 0xEAE2;
}

+ (KBFontAwesomeCode)xwUp {
    return 0xEAE3;
}

+ (KBFontAwesomeCode)xwThing {
    return 0xEAE4;
}

+ (KBFontAwesomeCode)xwDate {
    return 0xEAE5;
}

+ (KBFontAwesomeCode)xwSafe {
    return 0xEAE6;
}

+ (KBFontAwesomeCode)xwZhubian {
    return 0xEAE7;
}

+ (KBFontAwesomeCode)xwCheckin {
    return 0xEAE8;
}

+ (KBFontAwesomeCode)xwSunFaceicon {
    return 0xEAE9;
}

+ (KBFontAwesomeCode)xwMuteFaceicon {
    return 0xEAEA;
}

+ (KBFontAwesomeCode)xwDanmuWo {
    return 0xEAEB;
}

+ (KBFontAwesomeCode)xwZhenduan {
    return 0xEAEC;
}

+ (KBFontAwesomeCode)xwZhaiyao {
    return 0xEAED;
}

+ (KBFontAwesomeCode)xwJieyu {
    return 0xEAEE;
}

+ (KBFontAwesomeCode)xwFollowed {
    return 0xEAEF;
}

+ (KBFontAwesomeCode)xwPhTopic {
    return 0xEAF0;
}

+ (KBFontAwesomeCode)xwPhPlayback {
    return 0xEAF1;
}

+ (KBFontAwesomeCode)xwPhVip {
    return 0xEAF2;
}

+ (KBFontAwesomeCode)xwSharePoster {
    return 0xEAF3;
}

+ (KBFontAwesomeCode)xwClean {
    return 0xEAF4;
}

+ (KBFontAwesomeCode)xwListenLater {
    return 0xEAF5;
}

+ (KBFontAwesomeCode)xwpointM {
    return 0xEAF6;
}

+ (KBFontAwesomeCode)xwEye {
    return 0xEAF7;
}

+ (KBFontAwesomeCode)xwEye2 {
    return 0xEAF8;
}

+ (KBFontAwesomeCode)xwZhedie2 {
    return 0xEAF9;
}

+ (KBFontAwesomeCode)xwZhedie1 {
    return 0xEAFA;
}

+ (KBFontAwesomeCode)xwphoneFill {
    return 0xEAFB;
}

+ (KBFontAwesomeCode)xwH1 {
    return 0xEAFC;
}

+ (KBFontAwesomeCode)xwH2 {
    return 0xEAFD;
}

+ (KBFontAwesomeCode)xwVoiceBack {
    return 0xEAFE;
}

+ (KBFontAwesomeCode)xwFirePlus {
    return 0xEAFF;
}

+ (KBFontAwesomeCode)xwHome {
    return 0xEB00;
}

+ (KBFontAwesomeCode)xwWxStore {
    return 0xEB01;
}

+ (KBFontAwesomeCode)xwWxStoreTxt {
    return 0xEB02;
}

+ (KBFontAwesomeCode)xwDiscover {
    return 0xEB03;
}

+ (KBFontAwesomeCode)xwAiVoice {
    return 0xEB04;
}

+ (KBFontAwesomeCode)xwText {
    return 0xEB05;
}

+ (KBFontAwesomeCode)xwPodcastPrev {
    return 0xEB06;
}

+ (KBFontAwesomeCode)xwPodcastNext {
    return 0xEB07;
}

+ (KBFontAwesomeCode)xwMicFill {
    return 0xEB08;
}

+ (KBFontAwesomeCode)xwVideoHome {
    return 0xEB09;
}

+ (KBFontAwesomeCode)xwupBold {
    return 0xEB0A;
}

+ (KBFontAwesomeCode)ima {
    return 0xEB0B;
}

+ (KBFontAwesomeCode)xwDanyinhao1 {
    return 0xEB0C;
}

+ (KBFontAwesomeCode)xwDanyinhao2 {
    return 0xEB0D;
}

+ (KBFontAwesomeCode)xwvoice2Slash {
    return 0xEB0E;
}

+ (KBFontAwesomeCode)xwArrowUturnUnclosedSquare {
    return 0xEB14;
}

+ (KBFontAwesomeCode)xwRmbSquare {
    return 0xEB15;
}

+ (KBFontAwesomeCode)xwGift {
    return 0xEB0F;
}

+ (KBFontAwesomeCode)xwClothing {
    return 0xEB10;
}

+ (KBFontAwesomeCode)xwAiWaveRight {
    return 0xEB11;
}

+ (KBFontAwesomeCode)xwAiKeyborad {
    return 0xEB12;
}

+ (KBFontAwesomeCode)xwAiArrowDown {
    return 0xEB13;
}

+ (KBFontAwesomeCode)xwAiPaperplane {
    return 0xEB16;
}

+ (KBFontAwesomeCode)xwAiPhone {
    return 0xEB17;
}

+ (KBFontAwesomeCode)xwAiPhoneFill {
    return 0xEB18;
}

+ (KBFontAwesomeCode)xwPlay {
    return 0xEB19;
}

+ (KBFontAwesomeCode)xwm24Big {
    return 0xEB1A;
}

+ (KBFontAwesomeCode)xwMobiledata {
    return 0xEB1B;
}

+ (KBFontAwesomeCode)xwQywx {
    return 0xEB1C;
}

+ (KBFontAwesomeCode)xwTranslate {
    return 0xEB1D;
}

+ (KBFontAwesomeCode)xwnosoundStyle2 {
    return 0xEB1E;
}

+ (KBFontAwesomeCode)xwsoundFill {
    return 0xEB1F;
}

+ (KBFontAwesomeCode)xwAiKeyboard2 {
    return 0xEB20;
}

+ (KBFontAwesomeCode)xwTranslateC {
    return 0xEB21;
}

+ (KBFontAwesomeCode)xwTranslateE {
    return 0xEB22;
}

+ (KBFontAwesomeCode)xwvoice2Fill {
    return 0xEB23;
}

+ (KBFontAwesomeCode)xwSuspedRegular {
    return 0xEB24;
}

+ (KBFontAwesomeCode)xwCopyDone {
    return 0xEB25;
}

+ (KBFontAwesomeCode)xwHighlight {
    return 0xEB26;
}

+ (KBFontAwesomeCode)xwAdHaodian {
    return 0xEB27;
}

+ (KBFontAwesomeCode)xwAdR {
    return 0xEB28;
}


+ (BOOL)isValidCode:(KBFontAwesomeCode)code {
  return code >= [KBFontAwesomeResource xwarrowleft] && code <= [KBFontAwesomeResource xwAdR];
}
@end
